name: Terraform AWS Infrastructure

# on:
#   push:
#     branches:
#       - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      # -----------------------------
      # Checkout
      # -----------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # -----------------------------
      # Configure AWS using OIDC
      # -----------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # -----------------------------
      # Setup Terraform
      # -----------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -----------------------------
      # Terraform Init
      # -----------------------------
      - name: Terraform Init
        run: terraform init

      # -----------------------------
      # Terraform Format Check
      # -----------------------------
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # -----------------------------
      # Terraform Validate
      # -----------------------------
      - name: Terraform Validate
        run: terraform validate

      # -----------------------------
      # Terraform Plan
      # -----------------------------
      - name: Terraform Plan
        run: terraform plan

      # -----------------------------
      # Terraform Apply
      # -----------------------------
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve